var _ = require('underscore');
var S = require('string');

var choicesList = {
  age: [
    'Any',
    '16-25',
    '26-40',
    '41-64',
    '65+'
  ],
  purpose: {
    'anything': 'Anything',
    'start_business': 'Start A Business',
    'relocate_business': 'Relocate a Business',
    'hire_employees': 'Hire Employees / Interns',
    'train_employees': 'Training Employees',
    'buy_equipment': 'Buy Equipment',
    'open_location': 'Open a new location',
    'export': 'Export',
    'open_franchise': 'Open a franchise',
    'improve_commercial_property': 'Improve a commercial property',
    'buy_commercial_property': 'Buy a commercial property',
    'other': 'Other (Please specify below)'
  },
  businessType: [
    'For Profit Partnership or Corporation',
    'Non-Profit',
    'Sole Proprietor',
    'Any'
  ],
  yearsInBusiness:[
    'Any',
    'Less than 3 months',
    'Between 3 months and 1 year',
    '2 Years',
    '3 Years',
    '4+ Years',
  ],
  eligibleBusinessLocation: {
    'anywhere_in_pr': 'Anywhere In Puerto Rico',
    'municipality_in_pr': 'Municipality in Puerto Rico',
    'outside_of_pr': 'Outside of Puerto Rico',
    'other': 'Other (Please specify below)'
  },
  benefitType: {
    incentive: 'Incentive',
    loan: 'Loan',
    grant: 'Grant',
    salary_reimbursement: 'Salary Reimbursement',
    expertise: 'Expertise',
    other: 'Other (Please specify below)',
  },
  eligibleEntityTypes: {
    any: 'Any',
    non_profit: 'Non-Profit',
    for_profit: 'For-Profit',
    sole_proprietor: 'Sole Proprietor',
  },
  currentEmployeesRequired: [
    'Any',
    '1-5',
    '6-25',
    '26-50',
    '51-200',
    '200+'
  ],
  annualRevenue: [
    'Any',
    '0–99,999',
    '100,000-499,999',
    '500,000-999,999',
    '1 million-4.9 million',
    '5 million-9.9 million',
    'More than 10 million'
  ],
  eligibleIndustries: [
    'Any',
    'Agriculture',
    'Tourism',
    'Finance and Insurance',
    'Accommodation',
    'Food & Drink services',
    'Art, entertainment',
    'Construction',
    'Pharmaceuticals',
    'Biotechnology',
    'Wholesale Trade',
    'Health care',
    'Information / media / internet',
    'Public administration',
    'Real estate',
    'Transportation',
    'Retail',
    'Manufacture',
    'Auto repair',
    'Education',
    'Utilities',
    'Mining',
    'Professional, Scientific and Technical Services',
    'Management of Companies and Enterprises',
    'Administrative Support, Waste Management and Remediation Services'
  ],
  municipalities: [
  "Aguadilla",
  "Bayamon",
  "Cabo Rojo",
  "Caguas",
  "San juan",
  "Cidra",
  "Humacao",
  "Ponce",
  "Carolina",
  "Adjuntas",
  "Aguada",
  "Aguas Buenas",
  "Aibonito",
  "Anasco",
  "Arecibo",
  "Arroyo",
  "Barceloneta",
  "Barranquitas",
  "Camuy",
  "Canovanas",
  "Catano",
  "Cayey",
  "Ceiba",
  "Ciales",
  "Coamo",
  "Comerio",
  "Corozal",
  "Culebra",
  "Dorado",
  "Fajardo",
  "Florida",
  "Guanica",
  "Guayama",
  "Guayanilla",
  "Gurabo",
  "Hatillo",
  "Hormigueros",
  "Isabela",
  "Jayuya",
  "Juana Diaz",
  "Juncos",
  "Lajas",
  "Lares",
  "Las Marias",
  "Las Piedras",
  "Loiza",
  "Luquillo",
  "Manati",
  "Maricao",
  "Maunabo",
  "Mayaguez",
  "Moca",
  "Morovis",
  "Naguabo",
  "Naranjito",
  "Orocovis",
  "Patillas",
  "Penuelas",
  "Quebradillas",
  "Rincon",
  "Rio Grande",
  "Sabana Grande",
  "Salinas",
  "San German",
  "San Lorenzo",
  "San Sebastian",
  "Santa Isabel",
  "Toa Alta",
  "Toa Baja",
  "Trujillo Alto",
  "Utuado",
  "Vega Alta",
  "Vega Baja",
  "Vieques",
  "Villalba",
  "Yabucoa",
  "Yauco"
  ]
};

var associate = [
  'age',
  'currentEmployeesRequired'
];

exports = module.exports = choicesList;

